export type Country = {
  code: string;
  name_en: string;
  name_ja: string;
  flag: string;
  phone: string;
};

export const COUNTRIES: Country[] = [
  { code: "AF", name_en: "Afghanistan", name_ja: "アフガニスタン", flag: "🇦🇫", phone: "+93" },
  { code: "AL", name_en: "Albania", name_ja: "アルバニア", flag: "🇦🇱", phone: "+355" },
  { code: "DZ", name_en: "Algeria", name_ja: "アルジェリア", flag: "🇩🇿", phone: "+213" },
  { code: "AD", name_en: "Andorra", name_ja: "アンドラ", flag: "🇦🇩", phone: "+376" },
  { code: "AO", name_en: "Angola", name_ja: "アンゴラ", flag: "🇦🇴", phone: "+244" },
  { code: "AG", name_en: "Antigua and Barbuda", name_ja: "アンティグア・バーブーダ", flag: "🇦🇬", phone: "+1" },
  { code: "AR", name_en: "Argentina", name_ja: "アルゼンチン", flag: "🇦🇷", phone: "+54" },
  { code: "AM", name_en: "Armenia", name_ja: "アルメニア", flag: "🇦🇲", phone: "+374" },
  { code: "AU", name_en: "Australia", name_ja: "オーストラリア", flag: "🇦🇺", phone: "+61" },
  { code: "AT", name_en: "Austria", name_ja: "オーストリア", flag: "🇦🇹", phone: "+43" },
  { code: "AZ", name_en: "Azerbaijan", name_ja: "アゼルバイジャン", flag: "🇦🇿", phone: "+994" },
  { code: "BS", name_en: "Bahamas", name_ja: "バハマ", flag: "🇧🇸", phone: "+1" },
  { code: "BH", name_en: "Bahrain", name_ja: "バーレーン", flag: "🇧🇭", phone: "+973" },
  { code: "BD", name_en: "Bangladesh", name_ja: "バングラデシュ", flag: "🇧🇩", phone: "+880" },
  { code: "BB", name_en: "Barbados", name_ja: "バルバドス", flag: "🇧🇧", phone: "+1" },
  { code: "BY", name_en: "Belarus", name_ja: "ベラルーシ", flag: "🇧🇾", phone: "+375" },
  { code: "BE", name_en: "Belgium", name_ja: "ベルギー", flag: "🇧🇪", phone: "+32" },
  { code: "BZ", name_en: "Belize", name_ja: "ベリーズ", flag: "🇧🇿", phone: "+501" },
  { code: "BJ", name_en: "Benin", name_ja: "ベナン", flag: "🇧🇯", phone: "+229" },
  { code: "BT", name_en: "Bhutan", name_ja: "ブータン", flag: "🇧🇹", phone: "+975" },
  { code: "BO", name_en: "Bolivia", name_ja: "ボリビア", flag: "🇧🇴", phone: "+591" },
  { code: "BA", name_en: "Bosnia and Herzegovina", name_ja: "ボスニア・ヘルツェゴビナ", flag: "🇧🇦", phone: "+387" },
  { code: "BW", name_en: "Botswana", name_ja: "ボツワナ", flag: "🇧🇼", phone: "+267" },
  { code: "BR", name_en: "Brazil", name_ja: "ブラジル", flag: "🇧🇷", phone: "+55" },
  { code: "BN", name_en: "Brunei", name_ja: "ブルネイ", flag: "🇧🇳", phone: "+673" },
  { code: "BG", name_en: "Bulgaria", name_ja: "ブルガリア", flag: "🇧🇬", phone: "+359" },
  { code: "BF", name_en: "Burkina Faso", name_ja: "ブルキナファソ", flag: "🇧🇫", phone: "+226" },
  { code: "BI", name_en: "Burundi", name_ja: "ブルンジ", flag: "🇧🇮", phone: "+257" },
  { code: "KH", name_en: "Cambodia", name_ja: "カンボジア", flag: "🇰🇭", phone: "+855" },
  { code: "CM", name_en: "Cameroon", name_ja: "カメルーン", flag: "🇨🇲", phone: "+237" },
  { code: "CA", name_en: "Canada", name_ja: "カナダ", flag: "🇨🇦", phone: "+1" },
  { code: "CV", name_en: "Cape Verde", name_ja: "カーボベルデ", flag: "🇨🇻", phone: "+238" },
  { code: "CF", name_en: "Central African Republic", name_ja: "中央アフリカ", flag: "🇨🇫", phone: "+236" },
  { code: "TD", name_en: "Chad", name_ja: "チャド", flag: "🇹🇩", phone: "+235" },
  { code: "CL", name_en: "Chile", name_ja: "チリ", flag: "🇨🇱", phone: "+56" },
  { code: "CN", name_en: "China", name_ja: "中国", flag: "🇨🇳", phone: "+86" },
  { code: "CO", name_en: "Colombia", name_ja: "コロンビア", flag: "🇨🇴", phone: "+57" },
  { code: "KM", name_en: "Comoros", name_ja: "コモロ", flag: "🇰🇲", phone: "+269" },
  { code: "CG", name_en: "Congo", name_ja: "コンゴ共和国", flag: "🇨🇬", phone: "+242" },
  { code: "CD", name_en: "Congo (DRC)", name_ja: "コンゴ民主共和国", flag: "🇨🇩", phone: "+243" },
  { code: "CR", name_en: "Costa Rica", name_ja: "コスタリカ", flag: "🇨🇷", phone: "+506" },
  { code: "CI", name_en: "Côte d'Ivoire", name_ja: "コートジボワール", flag: "🇨🇮", phone: "+225" },
  { code: "HR", name_en: "Croatia", name_ja: "クロアチア", flag: "🇭🇷", phone: "+385" },
  { code: "CU", name_en: "Cuba", name_ja: "キューバ", flag: "🇨🇺", phone: "+53" },
  { code: "CY", name_en: "Cyprus", name_ja: "キプロス", flag: "🇨🇾", phone: "+357" },
  { code: "CZ", name_en: "Czech Republic", name_ja: "チェコ", flag: "🇨🇿", phone: "+420" },
  { code: "DK", name_en: "Denmark", name_ja: "デンマーク", flag: "🇩🇰", phone: "+45" },
  { code: "DJ", name_en: "Djibouti", name_ja: "ジブチ", flag: "🇩🇯", phone: "+253" },
  { code: "DM", name_en: "Dominica", name_ja: "ドミニカ国", flag: "🇩🇲", phone: "+1" },
  { code: "DO", name_en: "Dominican Republic", name_ja: "ドミニカ共和国", flag: "🇩🇴", phone: "+1" },
  { code: "EC", name_en: "Ecuador", name_ja: "エクアドル", flag: "🇪🇨", phone: "+593" },
  { code: "EG", name_en: "Egypt", name_ja: "エジプト", flag: "🇪🇬", phone: "+20" },
  { code: "SV", name_en: "El Salvador", name_ja: "エルサルバドル", flag: "🇸🇻", phone: "+503" },
  { code: "GQ", name_en: "Equatorial Guinea", name_ja: "赤道ギニア", flag: "🇬🇶", phone: "+240" },
  { code: "ER", name_en: "Eritrea", name_ja: "エリトリア", flag: "🇪🇷", phone: "+291" },
  { code: "EE", name_en: "Estonia", name_ja: "エストニア", flag: "🇪🇪", phone: "+372" },
  { code: "SZ", name_en: "Eswatini", name_ja: "エスワティニ", flag: "🇸🇿", phone: "+268" },
  { code: "ET", name_en: "Ethiopia", name_ja: "エチオピア", flag: "🇪🇹", phone: "+251" },
  { code: "FJ", name_en: "Fiji", name_ja: "フィジー", flag: "🇫🇯", phone: "+679" },
  { code: "FI", name_en: "Finland", name_ja: "フィンランド", flag: "🇫🇮", phone: "+358" },
  { code: "FR", name_en: "France", name_ja: "フランス", flag: "🇫🇷", phone: "+33" },
  { code: "GA", name_en: "Gabon", name_ja: "ガボン", flag: "🇬🇦", phone: "+241" },
  { code: "GM", name_en: "Gambia", name_ja: "ガンビア", flag: "🇬🇲", phone: "+220" },
  { code: "GE", name_en: "Georgia", name_ja: "ジョージア", flag: "🇬🇪", phone: "+995" },
  { code: "DE", name_en: "Germany", name_ja: "ドイツ", flag: "🇩🇪", phone: "+49" },
  { code: "GH", name_en: "Ghana", name_ja: "ガーナ", flag: "🇬🇭", phone: "+233" },
  { code: "GR", name_en: "Greece", name_ja: "ギリシャ", flag: "🇬🇷", phone: "+30" },
  { code: "GD", name_en: "Grenada", name_ja: "グレナダ", flag: "🇬🇩", phone: "+1" },
  { code: "GT", name_en: "Guatemala", name_ja: "グアテマラ", flag: "🇬🇹", phone: "+502" },
  { code: "GN", name_en: "Guinea", name_ja: "ギニア", flag: "🇬🇳", phone: "+224" },
  { code: "GW", name_en: "Guinea-Bissau", name_ja: "ギニアビサウ", flag: "🇬🇼", phone: "+245" },
  { code: "GY", name_en: "Guyana", name_ja: "ガイアナ", flag: "🇬🇾", phone: "+592" },
  { code: "HT", name_en: "Haiti", name_ja: "ハイチ", flag: "🇭🇹", phone: "+509" },
  { code: "HN", name_en: "Honduras", name_ja: "ホンジュラス", flag: "🇭🇳", phone: "+504" },
  { code: "HK", name_en: "Hong Kong", name_ja: "香港", flag: "🇭🇰", phone: "+852" },
  { code: "HU", name_en: "Hungary", name_ja: "ハンガリー", flag: "🇭🇺", phone: "+36" },
  { code: "IS", name_en: "Iceland", name_ja: "アイスランド", flag: "🇮🇸", phone: "+354" },
  { code: "IN", name_en: "India", name_ja: "インド", flag: "🇮🇳", phone: "+91" },
  { code: "ID", name_en: "Indonesia", name_ja: "インドネシア", flag: "🇮🇩", phone: "+62" },
  { code: "IR", name_en: "Iran", name_ja: "イラン", flag: "🇮🇷", phone: "+98" },
  { code: "IQ", name_en: "Iraq", name_ja: "イラク", flag: "🇮🇶", phone: "+964" },
  { code: "IE", name_en: "Ireland", name_ja: "アイルランド", flag: "🇮🇪", phone: "+353" },
  { code: "IL", name_en: "Israel", name_ja: "イスラエル", flag: "🇮🇱", phone: "+972" },
  { code: "IT", name_en: "Italy", name_ja: "イタリア", flag: "🇮🇹", phone: "+39" },
  { code: "JM", name_en: "Jamaica", name_ja: "ジャマイカ", flag: "🇯🇲", phone: "+1" },
  { code: "JP", name_en: "Japan", name_ja: "日本", flag: "🇯🇵", phone: "+81" },
  { code: "JO", name_en: "Jordan", name_ja: "ヨルダン", flag: "🇯🇴", phone: "+962" },
  { code: "KZ", name_en: "Kazakhstan", name_ja: "カザフスタン", flag: "🇰🇿", phone: "+7" },
  { code: "KE", name_en: "Kenya", name_ja: "ケニア", flag: "🇰🇪", phone: "+254" },
  { code: "KI", name_en: "Kiribati", name_ja: "キリバス", flag: "🇰🇮", phone: "+686" },
  { code: "KW", name_en: "Kuwait", name_ja: "クウェート", flag: "🇰🇼", phone: "+965" },
  { code: "KG", name_en: "Kyrgyzstan", name_ja: "キルギス", flag: "🇰🇬", phone: "+996" },
  { code: "LA", name_en: "Laos", name_ja: "ラオス", flag: "🇱🇦", phone: "+856" },
  { code: "LV", name_en: "Latvia", name_ja: "ラトビア", flag: "🇱🇻", phone: "+371" },
  { code: "LB", name_en: "Lebanon", name_ja: "レバノン", flag: "🇱🇧", phone: "+961" },
  { code: "LS", name_en: "Lesotho", name_ja: "レソト", flag: "🇱🇸", phone: "+266" },
  { code: "LR", name_en: "Liberia", name_ja: "リベリア", flag: "🇱🇷", phone: "+231" },
  { code: "LY", name_en: "Libya", name_ja: "リビア", flag: "🇱🇾", phone: "+218" },
  { code: "LI", name_en: "Liechtenstein", name_ja: "リヒテンシュタイン", flag: "🇱🇮", phone: "+423" },
  { code: "LT", name_en: "Lithuania", name_ja: "リトアニア", flag: "🇱🇹", phone: "+370" },
  { code: "LU", name_en: "Luxembourg", name_ja: "ルクセンブルク", flag: "🇱🇺", phone: "+352" },
  { code: "MO", name_en: "Macau", name_ja: "マカオ", flag: "🇲🇴", phone: "+853" },
  { code: "MG", name_en: "Madagascar", name_ja: "マダガスカル", flag: "🇲🇬", phone: "+261" },
  { code: "MW", name_en: "Malawi", name_ja: "マラウイ", flag: "🇲🇼", phone: "+265" },
  { code: "MY", name_en: "Malaysia", name_ja: "マレーシア", flag: "🇲🇾", phone: "+60" },
  { code: "MV", name_en: "Maldives", name_ja: "モルディブ", flag: "🇲🇻", phone: "+960" },
  { code: "ML", name_en: "Mali", name_ja: "マリ", flag: "🇲🇱", phone: "+223" },
  { code: "MT", name_en: "Malta", name_ja: "マルタ", flag: "🇲🇹", phone: "+356" },
  { code: "MH", name_en: "Marshall Islands", name_ja: "マーシャル諸島", flag: "🇲🇭", phone: "+692" },
  { code: "MR", name_en: "Mauritania", name_ja: "モーリタニア", flag: "🇲🇷", phone: "+222" },
  { code: "MU", name_en: "Mauritius", name_ja: "モーリシャス", flag: "🇲🇺", phone: "+230" },
  { code: "MX", name_en: "Mexico", name_ja: "メキシコ", flag: "🇲🇽", phone: "+52" },
  { code: "FM", name_en: "Micronesia", name_ja: "ミクロネシア", flag: "🇫🇲", phone: "+691" },
  { code: "MD", name_en: "Moldova", name_ja: "モルドバ", flag: "🇲🇩", phone: "+373" },
  { code: "MC", name_en: "Monaco", name_ja: "モナコ", flag: "🇲🇨", phone: "+377" },
  { code: "MN", name_en: "Mongolia", name_ja: "モンゴル", flag: "🇲🇳", phone: "+976" },
  { code: "ME", name_en: "Montenegro", name_ja: "モンテネグロ", flag: "🇲🇪", phone: "+382" },
  { code: "MA", name_en: "Morocco", name_ja: "モロッコ", flag: "🇲🇦", phone: "+212" },
  { code: "MZ", name_en: "Mozambique", name_ja: "モザンビーク", flag: "🇲🇿", phone: "+258" },
  { code: "MM", name_en: "Myanmar", name_ja: "ミャンマー", flag: "🇲🇲", phone: "+95" },
  { code: "NA", name_en: "Namibia", name_ja: "ナミビア", flag: "🇳🇦", phone: "+264" },
  { code: "NR", name_en: "Nauru", name_ja: "ナウル", flag: "🇳🇷", phone: "+674" },
  { code: "NP", name_en: "Nepal", name_ja: "ネパール", flag: "🇳🇵", phone: "+977" },
  { code: "NL", name_en: "Netherlands", name_ja: "オランダ", flag: "🇳🇱", phone: "+31" },
  { code: "NZ", name_en: "New Zealand", name_ja: "ニュージーランド", flag: "🇳🇿", phone: "+64" },
  { code: "NI", name_en: "Nicaragua", name_ja: "ニカラグア", flag: "🇳🇮", phone: "+505" },
  { code: "NE", name_en: "Niger", name_ja: "ニジェール", flag: "🇳🇪", phone: "+227" },
  { code: "NG", name_en: "Nigeria", name_ja: "ナイジェリア", flag: "🇳🇬", phone: "+234" },
  { code: "KP", name_en: "North Korea", name_ja: "北朝鮮", flag: "🇰🇵", phone: "+850" },
  { code: "MK", name_en: "North Macedonia", name_ja: "北マケドニア", flag: "🇲🇰", phone: "+389" },
  { code: "NO", name_en: "Norway", name_ja: "ノルウェー", flag: "🇳🇴", phone: "+47" },
  { code: "OM", name_en: "Oman", name_ja: "オマーン", flag: "🇴🇲", phone: "+968" },
  { code: "PK", name_en: "Pakistan", name_ja: "パキスタン", flag: "🇵🇰", phone: "+92" },
  { code: "PW", name_en: "Palau", name_ja: "パラオ", flag: "🇵🇼", phone: "+680" },
  { code: "PS", name_en: "Palestine", name_ja: "パレスチナ", flag: "🇵🇸", phone: "+970" },
  { code: "PA", name_en: "Panama", name_ja: "パナマ", flag: "🇵🇦", phone: "+507" },
  { code: "PG", name_en: "Papua New Guinea", name_ja: "パプアニューギニア", flag: "🇵🇬", phone: "+675" },
  { code: "PY", name_en: "Paraguay", name_ja: "パラグアイ", flag: "🇵🇾", phone: "+595" },
  { code: "PE", name_en: "Peru", name_ja: "ペルー", flag: "🇵🇪", phone: "+51" },
  { code: "PH", name_en: "Philippines", name_ja: "フィリピン", flag: "🇵🇭", phone: "+63" },
  { code: "PL", name_en: "Poland", name_ja: "ポーランド", flag: "🇵🇱", phone: "+48" },
  { code: "PT", name_en: "Portugal", name_ja: "ポルトガル", flag: "🇵🇹", phone: "+351" },
  { code: "QA", name_en: "Qatar", name_ja: "カタール", flag: "🇶🇦", phone: "+974" },
  { code: "RO", name_en: "Romania", name_ja: "ルーマニア", flag: "🇷🇴", phone: "+40" },
  { code: "RU", name_en: "Russia", name_ja: "ロシア", flag: "🇷🇺", phone: "+7" },
  { code: "RW", name_en: "Rwanda", name_ja: "ルワンダ", flag: "🇷🇼", phone: "+250" },
  { code: "KN", name_en: "Saint Kitts and Nevis", name_ja: "セントクリストファー・ネイビス", flag: "🇰🇳", phone: "+1" },
  { code: "LC", name_en: "Saint Lucia", name_ja: "セントルシア", flag: "🇱🇨", phone: "+1" },
  { code: "VC", name_en: "Saint Vincent", name_ja: "セントビンセント", flag: "🇻🇨", phone: "+1" },
  { code: "WS", name_en: "Samoa", name_ja: "サモア", flag: "🇼🇸", phone: "+685" },
  { code: "SM", name_en: "San Marino", name_ja: "サンマリノ", flag: "🇸🇲", phone: "+378" },
  { code: "ST", name_en: "São Tomé and Príncipe", name_ja: "サントメ・プリンシペ", flag: "🇸🇹", phone: "+239" },
  { code: "SA", name_en: "Saudi Arabia", name_ja: "サウジアラビア", flag: "🇸🇦", phone: "+966" },
  { code: "SN", name_en: "Senegal", name_ja: "セネガル", flag: "🇸🇳", phone: "+221" },
  { code: "RS", name_en: "Serbia", name_ja: "セルビア", flag: "🇷🇸", phone: "+381" },
  { code: "SC", name_en: "Seychelles", name_ja: "セーシェル", flag: "🇸🇨", phone: "+248" },
  { code: "SL", name_en: "Sierra Leone", name_ja: "シエラレオネ", flag: "🇸🇱", phone: "+232" },
  { code: "SG", name_en: "Singapore", name_ja: "シンガポール", flag: "🇸🇬", phone: "+65" },
  { code: "SK", name_en: "Slovakia", name_ja: "スロバキア", flag: "🇸🇰", phone: "+421" },
  { code: "SI", name_en: "Slovenia", name_ja: "スロベニア", flag: "🇸🇮", phone: "+386" },
  { code: "SB", name_en: "Solomon Islands", name_ja: "ソロモン諸島", flag: "🇸🇧", phone: "+677" },
  { code: "SO", name_en: "Somalia", name_ja: "ソマリア", flag: "🇸🇴", phone: "+252" },
  { code: "ZA", name_en: "South Africa", name_ja: "南アフリカ", flag: "🇿🇦", phone: "+27" },
  { code: "KR", name_en: "South Korea", name_ja: "韓国", flag: "🇰🇷", phone: "+82" },
  { code: "SS", name_en: "South Sudan", name_ja: "南スーダン", flag: "🇸🇸", phone: "+211" },
  { code: "ES", name_en: "Spain", name_ja: "スペイン", flag: "🇪🇸", phone: "+34" },
  { code: "LK", name_en: "Sri Lanka", name_ja: "スリランカ", flag: "🇱🇰", phone: "+94" },
  { code: "SD", name_en: "Sudan", name_ja: "スーダン", flag: "🇸🇩", phone: "+249" },
  { code: "SR", name_en: "Suriname", name_ja: "スリナム", flag: "🇸🇷", phone: "+597" },
  { code: "SE", name_en: "Sweden", name_ja: "スウェーデン", flag: "🇸🇪", phone: "+46" },
  { code: "CH", name_en: "Switzerland", name_ja: "スイス", flag: "🇨🇭", phone: "+41" },
  { code: "SY", name_en: "Syria", name_ja: "シリア", flag: "🇸🇾", phone: "+963" },
  { code: "TW", name_en: "Taiwan", name_ja: "台湾", flag: "🇹🇼", phone: "+886" },
  { code: "TJ", name_en: "Tajikistan", name_ja: "タジキスタン", flag: "🇹🇯", phone: "+992" },
  { code: "TZ", name_en: "Tanzania", name_ja: "タンザニア", flag: "🇹🇿", phone: "+255" },
  { code: "TH", name_en: "Thailand", name_ja: "タイ", flag: "🇹🇭", phone: "+66" },
  { code: "TL", name_en: "Timor-Leste", name_ja: "東ティモール", flag: "🇹🇱", phone: "+670" },
  { code: "TG", name_en: "Togo", name_ja: "トーゴ", flag: "🇹🇬", phone: "+228" },
  { code: "TO", name_en: "Tonga", name_ja: "トンガ", flag: "🇹🇴", phone: "+676" },
  { code: "TT", name_en: "Trinidad and Tobago", name_ja: "トリニダード・トバゴ", flag: "🇹🇹", phone: "+1" },
  { code: "TN", name_en: "Tunisia", name_ja: "チュニジア", flag: "🇹🇳", phone: "+216" },
  { code: "TR", name_en: "Turkey", name_ja: "トルコ", flag: "🇹🇷", phone: "+90" },
  { code: "TM", name_en: "Turkmenistan", name_ja: "トルクメニスタン", flag: "🇹🇲", phone: "+993" },
  { code: "TV", name_en: "Tuvalu", name_ja: "ツバル", flag: "🇹🇻", phone: "+688" },
  { code: "UG", name_en: "Uganda", name_ja: "ウガンダ", flag: "🇺🇬", phone: "+256" },
  { code: "UA", name_en: "Ukraine", name_ja: "ウクライナ", flag: "🇺🇦", phone: "+380" },
  { code: "AE", name_en: "United Arab Emirates", name_ja: "アラブ首長国連邦", flag: "🇦🇪", phone: "+971" },
  { code: "GB", name_en: "United Kingdom", name_ja: "イギリス", flag: "🇬🇧", phone: "+44" },
  { code: "US", name_en: "United States", name_ja: "アメリカ", flag: "🇺🇸", phone: "+1" },
  { code: "UY", name_en: "Uruguay", name_ja: "ウルグアイ", flag: "🇺🇾", phone: "+598" },
  { code: "UZ", name_en: "Uzbekistan", name_ja: "ウズベキスタン", flag: "🇺🇿", phone: "+998" },
  { code: "VU", name_en: "Vanuatu", name_ja: "バヌアツ", flag: "🇻🇺", phone: "+678" },
  { code: "VA", name_en: "Vatican City", name_ja: "バチカン", flag: "🇻🇦", phone: "+39" },
  { code: "VE", name_en: "Venezuela", name_ja: "ベネズエラ", flag: "🇻🇪", phone: "+58" },
  { code: "VN", name_en: "Vietnam", name_ja: "ベトナム", flag: "🇻🇳", phone: "+84" },
  { code: "YE", name_en: "Yemen", name_ja: "イエメン", flag: "🇾🇪", phone: "+967" },
  { code: "ZM", name_en: "Zambia", name_ja: "ザンビア", flag: "🇿🇲", phone: "+260" },
  { code: "ZW", name_en: "Zimbabwe", name_ja: "ジンバブエ", flag: "🇿🇼", phone: "+263" },
];

// Popular countries shown at the top of the list
export const POPULAR_COUNTRY_CODES = [
  "JP", "US", "GB", "CN", "KR", "TW", "TH", "VN", "PH", "ID",
  "MY", "SG", "IN", "AU", "CA", "DE", "FR", "IT", "ES", "BR",
];

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}

export function getPhoneCodeByCountry(code: string): string {
  return COUNTRIES.find((c) => c.code === code)?.phone || "";
}
