var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/delete-account/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__11a~jc2._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0jab4e1.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yp87ok._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xnhk7m._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_delete-account_page_actions_11t05si.js")
R.m(81718)
module.exports=R.m(81718).exports
